before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: repin-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
  main: ./cmd/repin/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/repin.version={{.Version}} -X github.com/k1LoW/repin.commit={{.FullCommit}} -X github.com/k1LoW/repin.date={{.Date}} -X github.com/k1LoW/repin/version.Version={{.Version}}
-
  id: repin-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  main: ./cmd/repin/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/repin.version={{.Version}} -X github.com/k1LoW/repin.commit={{.FullCommit}} -X github.com/k1LoW/repin.date={{.Date}} -X github.com/k1LoW/repin/version.Version={{.Version}}
-
  id: repin-windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  main: ./cmd/repin/main.go
  ldflags:
    - -s -w -X github.com/k1LoW/repin.version={{.Version}} -X github.com/k1LoW/repin.commit={{.FullCommit}} -X github.com/k1LoW/repin.date={{.Date}} -X github.com/k1LoW/repin/version.Version={{.Version}}
archives:
-
  id: repin-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
-
  id: repin-binary
  name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
dockers:
  -
    goos: linux
    goarch: amd64
    image_templates:
      - 'ghcr.io/k1low/repin:v{{ .Version }}'
      - 'ghcr.io/k1low/repin:latest'
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/k1LoW/repin"
    extra_files:
      - scripts/entrypoint.sh
brews:
  -
    name: repin
    ids:
      - repin-archive
    tap:
      owner: k1LoW
      name: homebrew-tap
    commit_author:
      name: k1LoW
      email: k1lowxb@gmail.com
    homepage: https://github.com/k1LoW/repin
    description: repin is a tool to replace strings between keyword pair.
    license: MIT
    install: |
      bin.install 'repin'
nfpms:
  - id: repin-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - repin-linux
    homepage: https://github.com/k1LoW/repin
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: repin is a tool to replace strings between keyword pair.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
