version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: repin-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/repin.version={{.Version}} -X github.com/k1LoW/repin.commit={{.FullCommit}} -X github.com/k1LoW/repin.date={{.Date}} -X github.com/k1LoW/repin/version.Version={{.Version}}
  main: ./cmd/repin/main.go
-
  id: repin-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/repin.version={{.Version}} -X github.com/k1LoW/repin.commit={{.FullCommit}} -X github.com/k1LoW/repin.date={{.Date}} -X github.com/k1LoW/repin/version.Version={{.Version}}
  main: ./cmd/repin/main.go
-
  id: repin-windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/repin.version={{.Version}} -X github.com/k1LoW/repin.commit={{.FullCommit}} -X github.com/k1LoW/repin.date={{.Date}} -X github.com/k1LoW/repin/version.Version={{.Version}}
  main: ./cmd/repin/main.go
archives:
-
  id: repin-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - LICENSE
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    id: repin-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - repin-linux
    homepage: https://github.com/k1LoW/repin
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: repin is a tool to replace strings between keyword pair.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
release:
  draft: true
  replace_existing_draft: true
